name: Deploy

on:
  workflow_dispatch:
    inputs:
      pre:
        type: boolean
        default: true
      environment:
        description: 'Deployment environment'
        required: true
        default: 'eph'
      environment-name:
        type: string
        description: 'The environment name. It will be infered from the environment and brach if not specified'

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infra/rg
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run Azure CLI commands'
      run: |
            az account show
  
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Terraform with specified version on the runner
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: |
        echo "Deploying to ${{ github.event.inputs.environment }}"
        echo "Deploying to ${{ inputs.environment }}"
        terraform init -backend-config=../env/${{ inputs.environment }}/${{ inputs.environment }}-backend-rg.tfvars
