name: Deploy

on:
  workflow_dispatch:
    inputs:
      pre:
        type: boolean
        default: true
      environment:
        description: 'Deployment environment'
        required: true
        default: 'eph'
      environment-name:
        type: string
        description: 'The environment name. It will be infered from the environment and brach if not specified'
      backend-key:
        type: string
        description: 'Name of the stage file inside the azure blob storage'

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy
      run: |
        echo "Deploying to ${{ github.event.inputs.environment }}"
        echo "AZURE_CLIENT_ID is ${{ vars.AZURE_CLIENT_ID}}"
        echo "AZURE_SUBSCRIPTION_ID is ${{ vars.AZURE_SUBSCRIPTION_ID }}"
        echo "AZURE_TENANT_ID is ${{ vars.AZURE_TENANT_ID }}"
        echo "environmet-name is : ${{ github.event.inputs.environment-name }}"
        echo "backend-key is : ${{ github.event.inputs.backend-key }}"
